--CREATE FILE FORMATS
CREATE OR REPLACE FILE FORMAT myjsonformat
  TYPE = 'JSON'
  STRIP_OUTER_ARRAY = true;
  
--CSV
ALTER FILE FORMAT CSV_GENERIC 
  SET COMPRESSION = 'AUTO' 
      FIELD_DELIMITER = ',' 
      RECORD_DELIMITER = '\n' 
      SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = 'NONE' ;
